---
# main.yml - Ansible role: Nginx Reverse Proxy deployment (HTTP only)
#
# This role deploys the Nginx reverse proxy container for the Juice Shop stack.
#   - Ensures the /opt/nginx directory exists on the VM for config storage
#   - Copies the HTTP-only Nginx config (no SSL, no certs) to the VM
#   - Deploys the Nginx container with:
#       * Custom config mounted read-only
#       * Only port 80 exposed (HTTP)
#       * Connected to the internal Docker network (app_net)
#   - No SSL, no HTTPS, no certificate logic (all HTTPS is handled by the WAF)
#   - Idempotent and safe to re-run
#
# Security best practices:
#   - Nginx is not exposed directly to the internet
#   - Only the WAF container is exposed externally (HTTPS)
#   - All internal traffic is HTTP-only between WAF, Nginx, and Juice Shop
#
# This role is part of a defense-in-depth architecture.

- name: Ensure /opt/nginx directory exists
  file:
    path: /opt/nginx
    state: directory
    mode: '0755'
  become: true

- name: Copy Nginx config for HTTP reverse proxy
  copy:
    src: default.conf
    dest: /opt/nginx/default.conf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Deploy Nginx Reverse Proxy container (HTTP only)
  community.docker.docker_container:
    name: nginx-reverse-proxy
    image: nginx:latest
    state: started
    restart_policy: unless-stopped
    volumes:
      - /opt/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - name: app_net
